package view;


import controller.TransactionController;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import model.TransactionModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author HP
 */
public class cardless extends javax.swing.JFrame {
    TransactionModel TM = new TransactionModel();
    TransactionController TC = new TransactionController();
    private String notif;
    NumberFormat formatRp = NumberFormat.getCurrencyInstance(new Locale("in", "ID"));

    /**
     * Creates new form cardless
     */
    public cardless() {
        if ("Active".equals(TM.getStatusLogin())) {
            initComponents();
            display();
        } else {
            dispose();
            welcomeScreen ss = new welcomeScreen();
            ss.setVisible(true);
        }
    }

    public void display() {
        pan_tarTun.setVisible(false);
        pan_setTun.setVisible(false);
        lab_noRek.setText(TM.getNoRek());
        lab_saldo.setText(formatRp.format(TM.getSaldo()));
        lab_noRek1.setText(TM.getNoRek());
        lab_saldo1.setText(formatRp.format(TM.getSaldo()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pan_tarTun = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lab_noRek = new javax.swing.JLabel();
        lab_saldo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cb_nom = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        pan_setTun = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lab_noRek1 = new javax.swing.JLabel();
        lab_saldo1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_nom1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 40, 20));

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 100, 100));

        pan_tarTun.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nominal Penarikan:");

        lab_noRek.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_noRek.setText("###############");

        lab_saldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_saldo.setText("###############");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Dari Rekening:");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\SystemBank-StructureData\\images\\icon\\saldo.png")); // NOI18N

        cb_nom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "50.000,00", "100.000,00", "150.000,00", "200.000,00", "250.000,00", "500.000,00", "1.000.000,00", "1.500.000,00", "2.000.000,00", "2.500.000,00" }));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Tarik Tunai");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_tarTunLayout = new javax.swing.GroupLayout(pan_tarTun);
        pan_tarTun.setLayout(pan_tarTunLayout);
        pan_tarTunLayout.setHorizontalGroup(
            pan_tarTunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_tarTunLayout.createSequentialGroup()
                .addGroup(pan_tarTunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_tarTunLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4))
                    .addGroup(pan_tarTunLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lab_noRek))
                    .addGroup(pan_tarTunLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lab_saldo))
                    .addGroup(pan_tarTunLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5)
                        .addGap(5, 5, 5)
                        .addComponent(cb_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pan_tarTunLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pan_tarTunLayout.setVerticalGroup(
            pan_tarTunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_tarTunLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addComponent(lab_noRek)
                .addGap(0, 0, 0)
                .addComponent(lab_saldo)
                .addGap(10, 10, 10)
                .addGroup(pan_tarTunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(cb_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pan_tarTun, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 240));

        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 100, 100));

        pan_setTun.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Nominal Setor:");

        lab_noRek1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_noRek1.setText("###############");

        lab_saldo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_saldo1.setText("###############");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Dari Rekening:");

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\SystemBank-StructureData\\images\\icon\\saldo.png")); // NOI18N

        cb_nom1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "50.000,00", "100.000,00", "150.000,00", "200.000,00", "250.000,00", "500.000,00", "1.000.000,00", "1.500.000,00", "2.000.000,00", "2.500.000,00" }));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Setor Tunai");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_setTunLayout = new javax.swing.GroupLayout(pan_setTun);
        pan_setTun.setLayout(pan_setTunLayout);
        pan_setTunLayout.setHorizontalGroup(
            pan_setTunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_setTunLayout.createSequentialGroup()
                .addGroup(pan_setTunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_setTunLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel8))
                    .addGroup(pan_setTunLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lab_noRek1))
                    .addGroup(pan_setTunLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lab_saldo1))
                    .addGroup(pan_setTunLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pan_setTunLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel9)
                        .addGap(5, 5, 5)
                        .addComponent(cb_nom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pan_setTunLayout.setVerticalGroup(
            pan_setTunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_setTunLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel8)
                .addGap(5, 5, 5)
                .addComponent(lab_noRek1)
                .addGap(0, 0, 0)
                .addComponent(lab_saldo1)
                .addGap(10, 10, 10)
                .addGroup(pan_setTunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(cb_nom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pan_setTun, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 260, 240));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\SystemBank-StructureData\\images\\background\\cardless.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose();
        menu_nasabah mn = new menu_nasabah();
        mn.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        pan_tarTun.setVisible(true);
        pan_setTun.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (cb_nom.getSelectedItem().toString().equals("-")) {
            JOptionPane.showMessageDialog(null, "Maaf, Nominal belum diisi !");
            cb_nom.requestFocus();
        } else {
            try {
                String nominal = cb_nom.getSelectedItem().toString().replace(".", "").replace(",00", "");
                notif = TC.minusSaldo(TM.getNoRek(), nominal, "Tarik Tunai", "Berhasil");
                TC.setSaldoNew(TM.getNoRek());
                JOptionPane.showMessageDialog(null, notif, "Informasi", JOptionPane.INFORMATION_MESSAGE);
                dispose();
                menu_nasabah mn = new menu_nasabah();
                mn.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Nasabah gagal tarik tunai", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (cb_nom1.getSelectedItem().toString().equals("-")) {
            JOptionPane.showMessageDialog(null, "Maaf, Nominal belum diisi !");
            cb_nom1.requestFocus();
        } else {
            try {
                String nominal = cb_nom1.getSelectedItem().toString().replace(".", "").replace(",00", "");
                notif = TC.plusSaldo(TM.getNoRek(), nominal, "Setor Tunai", "Berhasil");
                TC.setSaldoNew(TM.getNoRek());
                JOptionPane.showMessageDialog(null, notif, "Informasi", JOptionPane.INFORMATION_MESSAGE);
                dispose();
                menu_nasabah mn = new menu_nasabah();
                mn.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Nasabah gagal setor tunai", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        pan_tarTun.setVisible(false);
        pan_setTun.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cardless.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cardless.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cardless.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cardless.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cardless().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_nom;
    private javax.swing.JComboBox<String> cb_nom1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lab_noRek;
    private javax.swing.JLabel lab_noRek1;
    private javax.swing.JLabel lab_saldo;
    private javax.swing.JLabel lab_saldo1;
    private javax.swing.JPanel pan_setTun;
    private javax.swing.JPanel pan_tarTun;
    // End of variables declaration//GEN-END:variables
}
