/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.TransactionController;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import model.TransactionModel;

/**
 *
 * @author HP
 */
public class LoginPage extends javax.swing.JFrame {

    TransactionController TC = new TransactionController();
    TransactionModel TM = new TransactionModel();
    String notif;

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_username = new javax.swing.JTextField();
        pf_password = new javax.swing.JPasswordField();
        lbl_register = new javax.swing.JLabel();
        lbl_exit = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        lbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_username.setBackground(new java.awt.Color(171, 237, 216));
        getContentPane().add(tf_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 298, 250, 27));

        pf_password.setBackground(new java.awt.Color(171, 237, 216));
        pf_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pf_passwordKeyPressed(evt);
            }
        });
        getContentPane().add(pf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 350, 250, 27));

        lbl_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_registerMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 420, 80, 30));

        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 630, 100, 40));

        btn_login.setBackground(new java.awt.Color(70, 205, 207));
        btn_login.setFont(new java.awt.Font("Sakkal Majalla", 1, 24)); // NOI18N
        btn_login.setText("Login");
        btn_login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(61, 132, 168)));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 390, 70, 25));

        lbl_background.setBackground(new java.awt.Color(65, 163, 184));
        lbl_background.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\SystemBank-StructureData\\images\\background\\Login Page.png")); // NOI18N
        getContentPane().add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_registerMouseClicked
        RegisterPage RP = new RegisterPage();
        RP.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_registerMouseClicked

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        notif = TC.checkLogin(tf_username.getText(), pf_password.getText());
        if (notif != null) {
            JOptionPane.showMessageDialog(null, notif, "Informasi", JOptionPane.INFORMATION_MESSAGE);
            tf_username.setText("");
            pf_password.setText("");
        } else if ("1".equals(TM.getRole()) && "Active".equals(TM.getStatusLogin())) {
            dispose();
            AdminPage AP = new AdminPage();
            AP.setVisible(true);
        } else if ("2".equals(TM.getRole()) && "Active".equals(TM.getStatusLogin())) {
            dispose();
            NasabahPage_LandingPage NP = new NasabahPage_LandingPage();
            NP.setVisible(true);
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void pf_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pf_passwordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            notif = TC.checkLogin(tf_username.getText(), pf_password.getText());
            if (notif != null) {
                JOptionPane.showMessageDialog(null, notif, "Informasi", JOptionPane.INFORMATION_MESSAGE);
                tf_username.setText("");
                pf_password.setText("");
            } else if ("1".equals(TM.getRole()) && "Active".equals(TM.getStatusLogin())) {
                dispose();
                AdminPage AP = new AdminPage();
                AP.setVisible(true);
            } else if ("2".equals(TM.getRole()) && "Active".equals(TM.getStatusLogin())) {
                dispose();
                NasabahPage_LandingPage NP = new NasabahPage_LandingPage();
                NP.setVisible(true);
            }
        }
    }//GEN-LAST:event_pf_passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_register;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
