package view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import controller.AdminController;
import controller.TransactionController;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import model.AdminModel;
import model.TransactionModel;
import service.AdminService;

/**
 *
 * @author HP
 */
public class m_transfer extends javax.swing.JFrame {

    TransactionModel TM = new TransactionModel();
    TransactionController TC = new TransactionController();
    AdminModel AM = new AdminModel();
    AdminService AS = new AdminService();
    AdminController AC = new AdminController(AS);
    private String notif, notif1;
    NumberFormat formatRp = NumberFormat.getCurrencyInstance(new Locale("in", "ID"));

    /**
     * Creates new form m_transfer
     */
    public m_transfer() {
        if ("Active".equals(TM.getStatusLogin())) {
            initComponents();
            display();
        } else {
            // menutup menu tanpa keluar dari aplikasi
            dispose();
            // memanggil form login
            welcomeScreen ss = new welcomeScreen();
            ss.setVisible(true);
        }
    }

    public void display() {
        lab_noRek.setText(TM.getNoRek());
        lab_saldo.setText(formatRp.format(TM.getSaldo()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_rekTuj = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_nom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lab_noRek = new javax.swing.JLabel();
        lab_saldo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Minimal Transfer Rp10.000");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 20));

        tf_rekTuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_rekTujActionPerformed(evt);
            }
        });
        getContentPane().add(tf_rekTuj, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\SystemBank-StructureData\\images\\icon\\saldo.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        getContentPane().add(tf_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 150, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(46, 46, 46));
        jLabel5.setText("Sumber dana");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(46, 46, 46));
        jLabel6.setText("Nominal Transfer");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        lab_noRek.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_noRek.setText("#################");
        getContentPane().add(lab_noRek, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        lab_saldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_saldo.setText("#################");
        getContentPane().add(lab_saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 40, 20));

        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 290, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(46, 46, 46));
        jLabel9.setText("Rekening Tujuan");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\SystemBank-StructureData\\images\\background\\mTransfer.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        dispose();
        menu_nasabah mn = new menu_nasabah();
        mn.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        if (tf_rekTuj.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, No.Rekening Tujuan belum diisi !");
            tf_rekTuj.requestFocus();
        } else if (tf_nom.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Nominal belum diisi !");
            tf_nom.requestFocus();
        } else if (Double.parseDouble(tf_nom.getText().trim().replace(".", "")) < 10000) {
            JOptionPane.showMessageDialog(null, "Maaf, Minimal Transfer Rp10.000");
            tf_nom.requestFocus();
        } else if (tf_rekTuj.getText().trim().equals(TM.getNoRek())) {
            JOptionPane.showMessageDialog(null, "Maaf Tidak Bisa Transfer ke Rekening Sendiri");
            tf_rekTuj.requestFocus();
        } else {
            try {
                String nom = tf_nom.getText().replace(".", "");
                notif = TC.minusSaldo(TM.getNoRek(), nom, "Transfer Keluar", ("ke " + tf_rekTuj.getText()));
                notif1 = TC.plusSaldo(tf_rekTuj.getText(), nom, "Transfer Masuk", "dari " + TM.getNoRek());
                JOptionPane.showMessageDialog(null, notif, "Informasi", JOptionPane.INFORMATION_MESSAGE);
                TC.setSaldoNew(TM.getNoRek());
                dispose();
                menu_nasabah mn = new menu_nasabah();
                mn.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Anda gagal transfer", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void tf_rekTujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_rekTujActionPerformed
        if (tf_rekTuj.getText().trim().equals(TM.getNoRek())) {
            JOptionPane.showMessageDialog(null, "Maaf Tidak Bisa Transfer ke Rekening Sendiri");
            tf_nom.setEditable(false);
        } else {
            String namaLengkap = null;
            AC.viewAllNasabah();
            ArrayList<String[]> dataNasabah = AM.getDataNasabah();
            for (String[] rowData : dataNasabah) {
                if (rowData[0].equals(tf_rekTuj.getText())) {
                    namaLengkap = rowData[1];
                    break;
                }
            }
            if (namaLengkap == null) {
                JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
                tf_nom.setEditable(false);
                tf_rekTuj.requestFocus();
            } else {
                tf_nom.setEditable(true);
                int pilihan = JOptionPane.showConfirmDialog(null, "Apakah anda transfer ke atas nama\n" + namaLengkap, "Trasnfer", JOptionPane.YES_NO_OPTION);
                if (pilihan == JOptionPane.YES_OPTION) {
                    tf_nom.requestFocus();
                } else {
                    tf_rekTuj.setText("");
                }
            }
        }
    }//GEN-LAST:event_tf_rekTujActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(m_transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(m_transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(m_transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(m_transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new m_transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lab_noRek;
    private javax.swing.JLabel lab_saldo;
    private javax.swing.JTextField tf_nom;
    private javax.swing.JTextField tf_rekTuj;
    // End of variables declaration//GEN-END:variables
}
