/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.NasabahController;
import java.sql.ResultSet;
import java.text.NumberFormat;
import java.util.LinkedList;
import java.util.Locale;
import javax.swing.JOptionPane;
import model.NasabahModel;
import model.TransactionModel;

/**
 *
 * @author HP
 */
public class NasabahPage_LandingPage extends javax.swing.JFrame {
    private ResultSet rs;
    NumberFormat formatRp = NumberFormat.getCurrencyInstance(new Locale("in", "ID"));
    TransactionModel TM = new TransactionModel();
    NasabahModel NM = new NasabahModel();
    NasabahController NC = new NasabahController();
    
    /**
     * Creates new form NasabahPage
     */
    public NasabahPage_LandingPage() {
        if ("Active".equals(TM.getStatusLogin())) {
            initComponents();
            display();
        } else {
            dispose();
            LoginPage LP = new LoginPage();
            LP.setVisible(true);
        }
    }
    
    public void display() {
        lbl_namaLengkap.setText(TM.getNamaLengkap());
        lbl_noRek.setText(TM.getNoRek());
        lbl_saldo.setText(formatRp.format(TM.getSaldo()));
        try {
            NC.viewTransactionNasabah(TM.getNoRek());
            LinkedList<String[]> dataTransaction = NM.getDataTransaction();
            for (String[] rowData : dataTransaction) {
                rowData[2] = formatRp.format(Double.parseDouble(rowData[2]));
                String datas = rowData[1] + "\t\t" + rowData[2] + "\n" + rowData[0] + "\t" + rowData[3] + "\n---------------------------------------------------------------------\n";
                txa_riwayat.append(datas);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_namaLengkap = new javax.swing.JLabel();
        lbl_noRek = new javax.swing.JLabel();
        lbl_saldo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa_riwayat = new javax.swing.JTextArea();
        lbl_exit = new javax.swing.JLabel();
        lbl_cardless = new javax.swing.JLabel();
        lbl_transfer = new javax.swing.JLabel();
        lbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_namaLengkap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_namaLengkap.setText("Nama Lengkap Nasabah");
        getContentPane().add(lbl_namaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 100, -1, -1));

        lbl_noRek.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        lbl_noRek.setForeground(new java.awt.Color(255, 255, 255));
        lbl_noRek.setText("##############");
        getContentPane().add(lbl_noRek, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 205, 210, 30));

        lbl_saldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_saldo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_saldo.setText("###########");
        getContentPane().add(lbl_saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 270, -1, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "   Transaction History", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setName(""); // NOI18N

        txa_riwayat.setEditable(false);
        txa_riwayat.setBackground(new java.awt.Color(8, 89, 127));
        txa_riwayat.setColumns(20);
        txa_riwayat.setForeground(new java.awt.Color(255, 255, 255));
        txa_riwayat.setRows(5);
        txa_riwayat.setBorder(null);
        txa_riwayat.setCaretColor(java.awt.Color.darkGray);
        txa_riwayat.setSelectionColor(java.awt.Color.darkGray);
        jScrollPane1.setViewportView(txa_riwayat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 325, 250));

        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 7, 60, 24));

        lbl_cardless.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_cardlessMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_cardless, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 308, 70, 70));

        lbl_transfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_transferMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_transfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 67, 67));

        lbl_background.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\SystemBank-StructureData\\images\\background\\Nasabah Page - Landing Page.png")); // NOI18N
        getContentPane().add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        int pilihan = JOptionPane.showConfirmDialog(null, "Apakah anda ingin keluar?", "Keluar", JOptionPane.YES_NO_OPTION);
        if (pilihan == JOptionPane.YES_OPTION) {
            dispose();
            LoginPage LP = new LoginPage();
            LP.setVisible(true);
        }
        TM.setStatusLogin(null);
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void lbl_cardlessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cardlessMouseClicked
        dispose();
        NasabahPage_Cardless cl = new NasabahPage_Cardless();
        cl.setVisible(true);
    }//GEN-LAST:event_lbl_cardlessMouseClicked

    private void lbl_transferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_transferMouseClicked
        dispose();
        NasabahPage_Transfer tf = new NasabahPage_Transfer();
        tf.setVisible(true);
    }//GEN-LAST:event_lbl_transferMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NasabahPage_LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NasabahPage_LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NasabahPage_LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NasabahPage_LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NasabahPage_LandingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_cardless;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_namaLengkap;
    private javax.swing.JLabel lbl_noRek;
    private javax.swing.JLabel lbl_saldo;
    private javax.swing.JLabel lbl_transfer;
    private javax.swing.JTextArea txa_riwayat;
    // End of variables declaration//GEN-END:variables
}
