/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.TransactionController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import java.util.Random;
import javax.swing.JOptionPane;
import model.TransactionModel;

/**
 *
 * @author HP
 */
public class NasabahPage_tarTun_kodePenarikan extends javax.swing.JFrame {

    TransactionModel TM = new TransactionModel();
    TransactionController TC = new TransactionController();
    private String notif;
    private String nominal;

    /**
     * Creates new form NasabahPage_kodePenarikan
     */
    public NasabahPage_tarTun_kodePenarikan(String nominal) {
        if ("Active".equals(TM.getStatusLogin())) {
            initComponents();
            this.nominal = nominal;
            display();
        } else {
            dispose();
            LoginPage LP = new LoginPage();
            LP.setVisible(true);
        }
    }

    public void display() {
        lab_noRek.setText(TM.getNoRek());
        Random random = new Random();
        int[] randomNumbers = new int[6];
        String formattedNumbers = "";
        for (int i = 0; i < 6; i++) {
            randomNumbers[i] = random.nextInt(10);
            formattedNumbers += randomNumbers[i];
        }

        lab_kodePenarikan.setText(formattedNumbers);

        Timer timer = new Timer(1000, new ActionListener() {
            int timet = 4 * 60 + 59;

            @Override
            public void actionPerformed(ActionEvent e) {
                if (timet >= 0) {
                    int minutes = timet / 60;
                    int seconds = timet % 60;

                    String menit = String.format("%02d", minutes);
                    String detik = seconds < 10 ? "0" + seconds : String.format("%02d", seconds);

                    lab_timeCounter.setText(menit + " Menit " + detik + " detik");
                    timet--;
                } else {
                    ((Timer) e.getSource()).stop();
                    dispose();
                    NasabahPage_LandingPage LP = new NasabahPage_LandingPage();
                    LP.setVisible(true);
                }
            }

        });

        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lab_noRek = new javax.swing.JLabel();
        lab_penarikan = new javax.swing.JLabel();
        lab_kodePenarikan = new javax.swing.JLabel();
        lab_timeCounter = new javax.swing.JLabel();
        btn_cashWithdrawal = new javax.swing.JButton();
        lab_cancelWithdrawal = new javax.swing.JLabel();
        lbl_back = new javax.swing.JLabel();
        lab_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lab_noRek.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_noRek.setForeground(new java.awt.Color(255, 255, 255));
        lab_noRek.setText("###############");
        getContentPane().add(lab_noRek, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        lab_penarikan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_penarikan.setForeground(new java.awt.Color(255, 255, 255));
        lab_penarikan.setText("ATM");
        getContentPane().add(lab_penarikan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        lab_kodePenarikan.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lab_kodePenarikan.setForeground(new java.awt.Color(255, 255, 255));
        lab_kodePenarikan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lab_kodePenarikan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 400, 61));

        lab_timeCounter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lab_timeCounter.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lab_timeCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 349, 110, 20));

        btn_cashWithdrawal.setBackground(new java.awt.Color(72, 70, 109));
        btn_cashWithdrawal.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btn_cashWithdrawal.setForeground(new java.awt.Color(171, 237, 216));
        btn_cashWithdrawal.setText("OK");
        btn_cashWithdrawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cashWithdrawalActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cashWithdrawal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 405, 300, 27));

        lab_cancelWithdrawal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab_cancelWithdrawalMouseClicked(evt);
            }
        });
        getContentPane().add(lab_cancelWithdrawal, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 437, 130, 20));

        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_backMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 24, 25, 25));

        lab_background.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\SystemBank-StructureData\\images\\background\\Nasabah Page - Cardless - Cash Withdrawal.png")); // NOI18N
        getContentPane().add(lab_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cashWithdrawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cashWithdrawalActionPerformed
        try {
            notif = TC.minusSaldo(TM.getNoRek(), nominal, "Tarik Tunai", "Berhasil");
            TC.setSaldoNew(TM.getNoRek());
            JOptionPane.showMessageDialog(null, notif, "Informasi", JOptionPane.INFORMATION_MESSAGE);
            dispose();
            NasabahPage_LandingPage LP = new NasabahPage_LandingPage();
            LP.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nasabah gagal tarik tunai", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_cashWithdrawalActionPerformed

    private void lab_cancelWithdrawalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab_cancelWithdrawalMouseClicked
        dispose();
        NasabahPage_LandingPage LP = new NasabahPage_LandingPage();
        LP.setVisible(true);
    }//GEN-LAST:event_lab_cancelWithdrawalMouseClicked

    private void lbl_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseClicked
        dispose();
        NasabahPage_LandingPage LP = new NasabahPage_LandingPage();
        LP.setVisible(true);
    }//GEN-LAST:event_lbl_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NasabahPage_tarTun_kodePenarikan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NasabahPage_tarTun_kodePenarikan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NasabahPage_tarTun_kodePenarikan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NasabahPage_tarTun_kodePenarikan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cashWithdrawal;
    private javax.swing.JLabel lab_background;
    private javax.swing.JLabel lab_cancelWithdrawal;
    private javax.swing.JLabel lab_kodePenarikan;
    private javax.swing.JLabel lab_noRek;
    private javax.swing.JLabel lab_penarikan;
    private javax.swing.JLabel lab_timeCounter;
    private javax.swing.JLabel lbl_back;
    // End of variables declaration//GEN-END:variables
}
