/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.TransactionController;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class RegisterPage extends javax.swing.JFrame {
    
    TransactionController TC = new TransactionController();
    String notif;
    /**
     * Creates new form RegisterPage
     */
    public RegisterPage() {
        initComponents();
    }
    
    public void reset() {
        tf_namaLengkap.setText("");
        tf_username.setText("");
        pf_password.setText("");
        tf_noTelp.setText("");
        tf_email.setText("");
        tf_saldo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_namaLengkap = new javax.swing.JTextField();
        tf_username = new javax.swing.JTextField();
        pf_password = new javax.swing.JPasswordField();
        tf_noTelp = new javax.swing.JTextField();
        tf_email = new javax.swing.JTextField();
        tf_saldo = new javax.swing.JTextField();
        btn_register = new javax.swing.JButton();
        lbl_exit = new javax.swing.JLabel();
        lbl_login = new javax.swing.JLabel();
        lbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_namaLengkap.setBackground(new java.awt.Color(171, 237, 216));
        tf_namaLengkap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(61, 132, 168)));
        getContentPane().add(tf_namaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 220, 250, 27));

        tf_username.setBackground(new java.awt.Color(171, 237, 216));
        tf_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(61, 132, 168)));
        getContentPane().add(tf_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 270, 250, 27));

        pf_password.setBackground(new java.awt.Color(171, 237, 216));
        pf_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(61, 132, 168)));
        getContentPane().add(pf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 320, 250, 27));

        tf_noTelp.setBackground(new java.awt.Color(171, 237, 216));
        tf_noTelp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(61, 132, 168)));
        getContentPane().add(tf_noTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 370, 250, 27));

        tf_email.setBackground(new java.awt.Color(171, 237, 216));
        tf_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(61, 132, 168)));
        getContentPane().add(tf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 420, 250, 27));

        tf_saldo.setBackground(new java.awt.Color(171, 237, 216));
        tf_saldo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(61, 132, 168)));
        tf_saldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_saldoKeyPressed(evt);
            }
        });
        getContentPane().add(tf_saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 470, 250, 27));

        btn_register.setBackground(new java.awt.Color(70, 205, 207));
        btn_register.setFont(new java.awt.Font("Sakkal Majalla", 1, 24)); // NOI18N
        btn_register.setText("Register");
        btn_register.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(61, 132, 168)));
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 510, 80, 27));

        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 630, 90, 40));

        lbl_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_loginMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 550, 80, 40));

        lbl_background.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\SystemBank-StructureData\\images\\background\\Register Page.png")); // NOI18N
        getContentPane().add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_loginMouseClicked
        LoginPage li = new LoginPage();
        li.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_loginMouseClicked

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        notif = TC.register(tf_namaLengkap.getText(), tf_username.getText(), pf_password.getText(), tf_noTelp.getText(), tf_email.getText(), tf_saldo.getText(), "2");
        JOptionPane.showMessageDialog(null, notif, "Informasi", JOptionPane.INFORMATION_MESSAGE);
        if ("Data Berhasil Dirubah".equals(notif)) {
            reset();
        }
    }//GEN-LAST:event_btn_registerActionPerformed

    private void tf_saldoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_saldoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            notif = TC.register(tf_namaLengkap.getText(), tf_username.getText(), pf_password.getText(), tf_noTelp.getText(), tf_email.getText(), tf_saldo.getText(), "2");
            JOptionPane.showMessageDialog(null, notif, "Informasi", JOptionPane.INFORMATION_MESSAGE);
            if ("Data Berhasil Dirubah".equals(notif)) {
                reset();
            }
        }
    }//GEN-LAST:event_tf_saldoKeyPressed

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbl_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_namaLengkap;
    private javax.swing.JTextField tf_noTelp;
    private javax.swing.JTextField tf_saldo;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
