/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
/**
 *
 * @author HP
 */
public class menu_nasabah extends javax.swing.JFrame {

    private ResultSet rs;
    main_sc sc = new main_sc();
    NumberFormat formatRp = NumberFormat.getCurrencyInstance(new Locale("in", "ID"));

    /**
     * Creates new form menu_nasabah
     */
    public menu_nasabah() {
        if (Session.getStatusLogin() == "AKTIF") {
            initComponents();
            display();
        } else {
            dispose();
            welcomeScreen ss = new welcomeScreen();
            ss.setVisible(true);
        }
    }

    public void display() {
        lab_namaLengkap.setText(Session.getNama_lengkap());
        lab_noRek.setText(Session.getNo_rek());
        lab_saldo.setText(formatRp.format(Session.getJumlah_Transaksi()));
        try {
            rs = sc.showActivityNasabah(Session.getNo_rek());
            while (rs.next()) {
                sc.setJenis_Transaksi(rs.getString("Jenis_Transaksi"));
                sc.setJumlah_Transaksi(rs.getDouble("Jumlah_Transaksi"));
                sc.setTanggal_Transaksi(rs.getString("Tanggal_Transaksi"));
                sc.setKeterangan(rs.getString("keterangan"));
                String tampil = "";
                tampil += (sc.getJenis_Transaksi() + "\t\t" + formatRp.format(sc.getJumlah_Transaksi()) + "\n" + sc.getTanggal_Transaksi() + "\t" + sc.getKeterangan() + "\n" + "---------------------------------------------------------------------\n");
                txa_riwayat.append(tampil);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lab_namaLengkap = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lab_noRek = new javax.swing.JLabel();
        lab_saldo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa_riwayat = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lab_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lab_namaLengkap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lab_namaLengkap.setText("#############################");
        getContentPane().add(lab_namaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/bankRud.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        lab_noRek.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        lab_noRek.setForeground(new java.awt.Color(255, 255, 255));
        lab_noRek.setText("##############");
        getContentPane().add(lab_noRek, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 210, 30));

        lab_saldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lab_saldo.setForeground(new java.awt.Color(255, 255, 255));
        lab_saldo.setText("###########");
        getContentPane().add(lab_saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 30, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Saldo ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Selamat Datang,");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "   Riwayat Transaksi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setName(""); // NOI18N

        txa_riwayat.setEditable(false);
        txa_riwayat.setBackground(new java.awt.Color(46, 46, 46));
        txa_riwayat.setColumns(20);
        txa_riwayat.setForeground(new java.awt.Color(255, 255, 255));
        txa_riwayat.setRows(5);
        txa_riwayat.setBorder(null);
        txa_riwayat.setCaretColor(java.awt.Color.darkGray);
        txa_riwayat.setSelectionColor(java.awt.Color.darkGray);
        jScrollPane1.setViewportView(txa_riwayat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 330, 230));

        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 70, 70));

        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 60, 70));

        lab_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu_nasabah.png"))); // NOI18N
        getContentPane().add(lab_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        int pilihan = JOptionPane.showConfirmDialog(null, "Apakah anda ingin keluar?", "Keluar", JOptionPane.YES_NO_OPTION);
        if (pilihan == JOptionPane.YES_OPTION) {
            dispose();
            masuk li = new masuk();
            li.setVisible(true);
        }
        Session.setStatusLogin(null);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        dispose();
        m_transfer tf = new m_transfer();
        tf.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        dispose();
        cardless cl = new cardless();
        cl.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_nasabah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_nasabah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_nasabah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_nasabah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_nasabah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lab_background;
    private javax.swing.JLabel lab_namaLengkap;
    private javax.swing.JLabel lab_noRek;
    private javax.swing.JLabel lab_saldo;
    private javax.swing.JTextArea txa_riwayat;
    // End of variables declaration//GEN-END:variables
}
